### ISSUE TITLE
python OpenGL issue.

### ISSUE THREAD

**Issue by wangg12** [DLR-RM/AugmentedAutoencoder#1]
I followed README to install the packages but got the following error:

`'glCreateTextures' is not defined`.

@MartinSmeyer Do you have any ideas?

**Comment by MartinSmeyer** [comment]
Are you running the code on a remote machine? Because currently headless rendering is not supported.

**Comment by wangg12** [comment]
@MartinSmeyer No, I am running it on local machine. I've checked the installed PyOpenGL, it seems some  functions not exist such as `glCreateTextures`. I installed it via pip as the README said.

**Comment by wangg12** [comment]
I managed using these functions by installing PyOpenGL from [https://github.com/mcfletch/PyOpenGL](https://github.com/mcfletch/PyOpenGL).

**Comment by SonOfCoding** [comment]
@wangg12 Hi, have you solved this problem? do you have wechat or qq for discussion?

**Comment by wangg12** [comment]
@SonOfCoding I can use the functions now as mentioned above. I don't know if there are other problems.

**Comment by sinnis1991** [comment]
@wangg12 I am sorry that the solution you provided did not work. After I re-installed pyopengl as you suggested, I tried to call
>>> glCreateTextures
<OpenGL.platform.baseplatform.glCreateTextures object at 0x7f16de11a050>
It seems that the updated version of pyopengl does add this function (or class)
but it's creepy that if i try to give it values for initializing: 
>>> glGenTextures(None,None,None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/sinnis/ADDDISK/pyopengl/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/media/sinnis/ADDDISK/pyopengl/OpenGL/wrapper.py", line 664, in wrapperCall
    cArgs = tuple(calculate_cArgs( pyArgs ))
  File "/media/sinnis/ADDDISK/pyopengl/OpenGL/wrapper.py", line 467, in calculate_cArgs
    yield converter( pyArgs, index, self )
  File "/media/sinnis/ADDDISK/pyopengl/OpenGL/converters.py", line 251, in __call__
    return super( SizedOutputOrInput,self ).__call__( pyArgs, index, baseOperation )
  File "/media/sinnis/ADDDISK/pyopengl/OpenGL/converters.py", line 196, in __call__
    return self.arrayType.zeros( self.getSize(pyArgs) )
  File "/media/sinnis/ADDDISK/pyopengl/OpenGL/arrays/arraydatatype.py", line 177, in zeros
    return cls.returnHandler().zeros( dims, typeCode or cls.typeConstant )
  File "/media/sinnis/ADDDISK/pyopengl/OpenGL/arrays/numpymodule.py", line 111, in zeros
    dims = numpy.array( dims, dtype='i')
TypeError: ("long() argument must be a string or a number, not 'NoneType'", 'Failure in cConverter <OpenGL.converters.SizedOutputOrInput object at 0x7f16de2f5050>', (None, None), 1, <OpenGL.platform.baseplatform.glGenTextures object at 0x7f16de37e9e0>)
>>> glCreateTextures(None,None,None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/sinnis/ADDDISK/pyopengl/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
  File "/media/sinnis/ADDDISK/pyopengl/OpenGL/wrapper.py", line 689, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/media/sinnis/ADDDISK/pyopengl/OpenGL/platform/baseplatform.py", line 414, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glCreateTextures, check for bool(glCreateTextures) before calling

It seems that the it is checking and considering this call an undefined function. That's how it raises problem in the script texture.py and I find that any glCreate* calls has this problem.

Still no solution to fix this problem.  Help!

**Comment by wangg12** [comment]
@sinnis1991 It did work for me on several machines with different environments. For example,
```
In [1]: import OpenGL
In [2]: OpenGL
Out[1]: <module 'OpenGL' from '/data/software/pyopengl/OpenGL/__init__.py'>
In [3]: from OpenGL.GL import *
In [4]: glCreateTextures
Out[2]: <OpenGL.platform.baseplatform.glCreateTextures at 0x7f94b7aab1f8>
```

**Comment by HuaWeitong** [comment]
> @wangg12 I am sorry that the solution you provided did not work. After I re-installed pyopengl as you suggested, I tried to call
> 
> > >>> glCreateTextures
> > <OpenGL.platform.baseplatform.glCreateTextures object at 0x7f16de11a050>
> 
> It seems that the updated version of pyopengl does add this function (or class)
> but it's creepy that if i try to give it values for initializing:
> 
> > >>> glCreateTextures(None,None,None)
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File "/media/sinnis/ADDDISK/pyopengl/OpenGL/latebind.py", line 41, in **call**
> > return self._finalCall( *args, **named )
> > File "/media/sinnis/ADDDISK/pyopengl/OpenGL/wrapper.py", line 689, in wrapperCall
> > result = wrappedOperation( *cArguments )
> > File "/media/sinnis/ADDDISK/pyopengl/OpenGL/platform/baseplatform.py", line 414, in **call**
> > self.**name**, self.**name**,
> > OpenGL.error.NullFunctionError: Attempt to call an undefined function glCreateTextures, check for bool(glCreateTextures) before calling
> 
> It seems that the it is checking and considering this call an undefined function. That's how it raises problem in the script texture.py and I find that any glCreate* calls has this problem.
> 
> Still no solution to fix this problem. Help!

Hi, I met the same problem, have you solved it?

**Comment by cqq0505** [comment]
> @wangg12 I am sorry that the solution you provided did not work. After I re-installed pyopengl as you suggested, I tried to call
> 
> >>> glCreateTextures
> <OpenGL.platform.baseplatform.glCreateTextures object at 0x7f16de11a050>
> 
> It seems that the updated version of pyopengl does add this function (or class)
> but it's creepy that if i try to give it values for initializing:
> 
> >>> glCreateTextures(None,None,None)
> Traceback (most recent call last):
> File "", line 1, in 
> File "/media/sinnis/ADDDISK/pyopengl/OpenGL/latebind.py", line 41, in call
> return self._finalCall( *args, **named )
> File "/media/sinnis/ADDDISK/pyopengl/OpenGL/wrapper.py", line 689, in wrapperCall
> result = wrappedOperation( *cArguments )
> File "/media/sinnis/ADDDISK/pyopengl/OpenGL/platform/baseplatform.py", line 414, in call
> self.name, self.name,
> OpenGL.error.NullFunctionError: Attempt to call an undefined function glCreateTextures, check for bool(glCreateTextures) before calling
> 
> It seems that the it is checking and considering this call an undefined function. That's how it raises problem in the script texture.py and I find that any glCreate* calls has this problem.
> Still no solution to fix this problem.  Help!



> @wangg12 I am sorry that the solution you provided did not work. After I re-installed pyopengl as you suggested, I tried to call
> 
> >>> glCreateTextures
> <OpenGL.platform.baseplatform.glCreateTextures object at 0x7f16de11a050>
> 
> It seems that the updated version of pyopengl does add this function (or class)
> but it's creepy that if i try to give it values for initializing:
> 
> >>> glCreateTextures(None,None,None)
> Traceback (most recent call last):
> File "", line 1, in 
> File "/media/sinnis/ADDDISK/pyopengl/OpenGL/latebind.py", line 41, in call
> return self._finalCall( *args, **named )
> File "/media/sinnis/ADDDISK/pyopengl/OpenGL/wrapper.py", line 689, in wrapperCall
> result = wrappedOperation( *cArguments )
> File "/media/sinnis/ADDDISK/pyopengl/OpenGL/platform/baseplatform.py", line 414, in call
> self.name, self.name,
> OpenGL.error.NullFunctionError: Attempt to call an undefined function glCreateTextures, check for bool(glCreateTextures) before calling
> 
> It seems that the it is checking and considering this call an undefined function. That's how it raises problem in the script texture.py and I find that any glCreate* calls has this problem.
> Still no solution to fix this problem.  Help!

Hi! I met the exactly same problem with you, did you solve it ?  I've tried re-installed pyopengl from https://github.com/mcfletch/PyOpenGL,  but it still doesn't work.

**Comment by cqq0505** [comment]
> @wangg12 I am sorry that the solution you provided did not work. After I re-installed pyopengl as you suggested, I tried to call
> 
> 
> 
> 
> glCreateTextures
> <OpenGL.platform.baseplatform.glCreateTextures object at 0x7f16de11a050>
> 
> 
> 
> 
> It seems that the updated version of pyopengl does add this function (or class)
> but it's creepy that if i try to give it values for initializing:
> 
> 
> 
> 
> glCreateTextures(None,None,None)
> Traceback (most recent call last):
> File "", line 1, in
> File "/media/sinnis/ADDDISK/pyopengl/OpenGL/latebind.py", line 41, in call
> return self._finalCall( *args, **named )
> File "/media/sinnis/ADDDISK/pyopengl/OpenGL/wrapper.py", line 689, in wrapperCall
> result = wrappedOperation( *cArguments )
> File "/media/sinnis/ADDDISK/pyopengl/OpenGL/platform/baseplatform.py", line 414, in call
> self.name, self.name,
> OpenGL.error.NullFunctionError: Attempt to call an undefined function glCreateTextures, check for bool(glCreateTextures) before calling
> 
> 
> 
> 
> It seems that the it is checking and considering this call an undefined function. That's how it raises problem in the script texture.py and I find that any glCreate* calls has this problem.
> Still no solution to fix this problem. Help!
> 
> Hi, I met the same problem, have you solved it?

Hey,did you solve the problem? I met the exactly same question.

**Comment by lingxiaoZHONG** [comment]
Problem may not from installing pyopengl, this work need at least OpenGL 4.5 version, but some GPU not support high version OpenGL. This work success in my NVIDIA 1080 GPU, but failed in my Intel GPU

**Comment by davideCremona** [comment]
I'm having the same problem, I have OpenGL 3.1.0 and Python3.6 (of course I have converted the code from Python2.7 to 3.6)
