### ISSUE TITLE
[question]what does bgr_normal means?

### ISSUE THREAD

**Issue by liuicheng123** [DLR-RM/AugmentedAutoencoder#101]
Dear researchers:
What does the bgr_normal means?
https://github.com/DLR-RM/AugmentedAutoencoder/blob/47a682c14fd3eaa65d737f7f86dc8feba8451425/auto_pose/meshrenderer/meshrenderer_phong_normals.py#L166
Thanks.

**Comment by MartinSmeyer** [comment]
Hi,

This means that a normal image is rendered. I have experimented a bit with that info but it is not part of the official approach. Problem is that in practice they are quite noisy.

**Comment by MartinSmeyer** [comment]
Hi,

This means that a normal image is rendered. I have experimented a bit with that info but it is not part of the official approach. Problem is that in practice they are quite noisy.

**Comment by liuicheng123** [comment]
> Hi,
> 
> This means that a normal image is rendered. I have experimented a bit with that info but it is not part of the official approach. Problem is that in practice they are quite noisy.

Hello.
is the normal image the **surface normal** image of the 3D point? 
thanks for your reply.

**Comment by MartinSmeyer** [comment]
yes
