### ISSUE TITLE
Symmetrical objects performance?

### ISSUE THREAD

**Issue by AnnaMelk** [DLR-RM/AugmentedAutoencoder#102]
Hi! First of all, thank you for the code and clear instructions on how to run it, the auto-encoder works pretty great on T-LESS models that I've tried. 
I wanted to ask if there are any ways I could make this model perform better with symmetrical models? It works okay with my own 3D model, but it struggles with determining the orientation/rotation sometimes (predicted rendered view doesn't match the cropped webcam input)

![Screenshot from 2022-01-26 14-37-26](https://user-images.githubusercontent.com/46524093/151174256-05c393d0-9224-47e2-ad33-f35ea5d28d83.png)
 
Any insights are appreciated. Thank you very much!

**Comment by MartinSmeyer** [comment]
For such colorful objects, it crucial that you are defining vertex color for your object surface as well. You can use e.g. Blender to define vertex colors on your 3D model:

https://www.youtube.com/watch?v=8mNk6r_bwxI
