### ISSUE TITLE
Questions about generating datasets

### ISSUE THREAD

**Issue by JZhao12** [DLR-RM/AugmentedAutoencoder#103]
Hi, Martin

sorry to disturb you, may I ask what kinds of rendering software you used to generate your database from different views in your method? I would like to generate some LineMod images like this:

![001276](https://user-images.githubusercontent.com/43590151/152447042-06806f19-5fdb-4667-a354-9d2fda32a965.png)

Specifically, I would like to first randomly create multiple rotation matrices, then apply these rotation matrices to objects' 3D models, and then get the rotated images. I noticed that your department has a rendering software called BlenderPro, is this convenient to generate images as I described above?

Thank you very much!
Jianyu

**Comment by MartinSmeyer** [comment]
Hi,

I created my own renderer in OpenGL, it is included under `auto_pose/meshrenderer`. However these days I would rely on [pyrender](https://pyrender.readthedocs.io/en/latest/index.html) for such simple rasterized images. 

You can also use our software BlenderProc to do that if you want more photorealistic renderings using ray tracing. 
https://github.com/DLR-RM/BlenderProc/tree/main/examples/basics/camera_object_pose

To obtain strong generalization performance you can also train on the BlenderProc scenes that we created for the BOP challenge.
https://github.com/DLR-RM/BlenderProc/blob/main/README_BlenderProc4BOP.md
