### ISSUE TITLE
[question]test dataset groud truth: t-less/t-less_v2/test_primesense_gt_stats/

### ISSUE THREAD

**Issue by qifengluo** [DLR-RM/AugmentedAutoencoder#105]
In the dataset web, there is no the test_primesense_gt_stats (http://ptak.felk.cvut.cz/6DB/public/bop_datasets/)
Every scense in test_primescense folder has gt.yaml, but it is not the same format with test code.

**Comment by MartinSmeyer** [comment]
The data format of the BOP challenge is different to what was used in the paper evaluation. The original data is unfortunately no longer available. If you want to compare, I would recommend using the BOP format as described here:

https://github.com/DLR-RM/AugmentedAutoencoder/tree/master#evaluate-a-model
