### ISSUE TITLE
Unavailable data?

### ISSUE THREAD

**Issue by shbe-aau** [DLR-RM/AugmentedAutoencoder#107]
Hello,

First of all, thank you for some really nice work and for providing the code!

I am trying to download some of the data like the pre-trained MP-Encoder and your T-LESS MaskRCNN predictions - but the links seems to have expired. Is it possible to re-upload the data?

What is unavailable/expired:
 - Pre-trained MP Encoder on object 1-18 of TLESS + codebooks for all 30 (paper)
 - MaskRCNN predictions for T-LESS
 - Pre-computed MaskRCNN predictions for all BOP datasets
 
Perhaps it is also possible to upload the pre-trained MaskRCNN models for both T-LESS and the BOP datasets?

Best regards,
Stefan

**Comment by MartinSmeyer** [comment]
Hi @shbe-aau ,

Thanks for the reminder. I have updated the links for the 

- Pre-computed MaskRCNN predictions for all BOP datasets 

and 

- Pre-trained MP Encoder on object 1-18 of TLESS + codebooks for all 30 (paper)

I can have a look for the pretrained MaskRCNN models for the BOP datasets but I would actually recommend you to use them from here:

https://github.com/ylabbe/cosypose#pre-trained-models-1

**Comment by MartinSmeyer** [comment]
(For evaluation I would suggest using the BOP datasets)

**Comment by shbe-aau** [comment]
Awesome - thank you!
