### ISSUE TITLE
[question] how to install sixd_toolkit as pip package

### ISSUE THREAD

**Issue by KSImperial** [DLR-RM/AugmentedAutoencoder#111]
In the sixd_toolkit_extensions/help.txt one is instructed to install the sixd_toolkit as pip package. May I ask for clarification on how to accomplish this due to no setup.py and empty init.py. 
Due to missing installation I am experiencing import issues for sixd_toolkit on Colab even when adding the path.

**Comment by MartinSmeyer** [comment]
Hey @KSImperial 
This is the old way, you would need to add the `setup.py` yourself or just add the package to your PYTHONPATH. 
However, the `sixd_toolkit` is deprecated and has been superseded by the `bop_toolkit`. So if you want to evaluate the method I would strongly advise you to use the [BOP challenge protocol](https://github.com/DLR-RM/AugmentedAutoencoder#reproducing-and-visualizing-bop-challenge-results) as this is how people compare methods in 2022. But adding the sixd_toolkit package to your path should work anyways, `__init__.py` is supposed to be empty.

**Comment by KSImperial** [comment]
Thank you very much!
