### ISSUE TITLE
Rotation Estimation Mismatch

### ISSUE THREAD

**Issue by RahulJain7** [DLR-RM/AugmentedAutoencoder#112]
I am trying to estimate the rotation matrix using a car model. I have tried adjusting various parameters in the config section example the camera matrix, resolution, radius. The problem I am facing is that the model predicts certain crops perfectly whereas for some crops the predictions are far from matching. Following are the results
![Screenshot from 2022-07-26 20-03-53](https://user-images.githubusercontent.com/13780713/181036872-2d1b72bb-9ea9-4410-af07-3145a0a2bbcf.png) Image Crop  
![Screenshot from 2022-07-26 20-04-06](https://user-images.githubusercontent.com/13780713/181037266-e2d1fd2c-678f-45c9-b729-679377f3dd65.png) Prediction

![Screenshot from 2022-07-26 20-07-08](https://user-images.githubusercontent.com/13780713/181037518-097a3dba-b227-48f5-8821-0dae42c22294.png)Image Crop
![Screenshot from 2022-07-26 20-07-19](https://user-images.githubusercontent.com/13780713/181037562-1ec2cafe-20b7-437d-9111-87332b0aca25.png) Prediction

![Screenshot from 2022-07-26 20-27-58](https://user-images.githubusercontent.com/13780713/181040275-04d8e2e1-30dc-4cda-b5fc-3db1b7f6305b.png) Image crop based on cad model (from Meshlab)
![Screenshot from 2022-07-26 20-28-05](https://user-images.githubusercontent.com/13780713/181040372-2d56c3c2-64d8-49f2-911f-d617d313b386.png)Prediction

As you can see the rotation estimate for the first crop is completely wrong where as the second one is almost perfect. Also, the image crops of any pose of the cad model (the third sample above) seems to work perfectly.  Likewise I have tried with many crops of real images but most of the predictions are far off. I have tried with various camera intrinsics and resolution but a lot of crops are predicted completely wrong. As for training i have taken all the default input like number of images iterations and training datasets. Is it because the real model has different textures at different parts unlike the cad model which is texture less (because crops of 3d model are working perfectly)? If yes, is there any way where i can increase the model accuracy ?

**Comment by MartinSmeyer** [comment]
Hi @RahulJain7,

> Is it because the real model has different textures at different parts unlike the cad model which is texture less (because crops of 3d model are working perfectly)? If yes, is there any way where i can increase the model accuracy ?

Yes that is the reason, it is an RGB method so you can't expect it to work well without the texture information if the object itself has texture. You can model the vertex colors for your specific car using Blender or some other software.

Here are some tutorials for Blender:
https://www.youtube.com/watch?v=8mNk6r_bwxI
https://www.youtube.com/watch?v=M9sgbxP6i78
