### ISSUE TITLE
> > > >I want to know how to train 2D detector with tless train-dataset

### ISSUE THREAD

**Issue by lxwkobe24** [DLR-RM/AugmentedAutoencoder#115]
> > > > 
> > > 
> > > 
> > > hello，Could you tell me how train 2D detector? Thank you so much~
> > 
> > 
> > I used [Detectron2](https://github.com/facebookresearch/detectron2) for that. Here is a [colab notebook](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5), where you can define a data set and start the training.
> > hello ,I want to know how to train 2D detector with tless train-dataset?
> > if you could reply me ,i will appreciate！

Hey maybe I can help you doing that but can you please open a new issue for that?

_Originally posted by @AminSeffo in https://github.com/DLR-RM/AugmentedAutoencoder/issues/113#issuecomment-1201109921_

**Comment by MartinSmeyer** [comment]
have a look here:
https://github.com/ylabbe/cosypose#bop20-models-and-results
