### ISSUE TITLE
How to limit the SO(3) rotation in the training set?

### ISSUE THREAD

**Issue by AminSeffo** [DLR-RM/AugmentedAutoencoder#117]
Hello @MartinSmeyer ,

For my use case, I don't really need all the rotations which can be generated by creating the codebook, and because I have problems with recognition and the rotations don't match (see the image below):

![Screenshot from 2022-08-23 13-46-17](https://user-images.githubusercontent.com/92951154/186150159-4e30830a-228f-4f89-85e4-0839f58c8ea8.png)
So the AAE does not match the alignment along the x-axis up to +180°. My idea is to constrain the alignments as follows:

X-axis and Y-axis = **[-45,45]**
Z-axis = **[-180,+180]**

I have noticed that the training set contains too many images from this **wrong** position that could produce this prediction, so my question is how to limit the orientations in the config file?

Here some images from actual the training set:

![Screenshot from 2022-08-23 13-42-23](https://user-images.githubusercontent.com/92951154/186151851-12370e5b-f0fd-4d3d-becf-1f7c803bf788.png)
![Screenshot from 2022-08-23 13-42-26](https://user-images.githubusercontent.com/92951154/186151854-7b3eb8a1-6918-4467-869c-4e5d00e47b45.png)

This is how the object  is oriented with Meshlab: 

![Screenshot from 2022-08-23 13-43-58](https://user-images.githubusercontent.com/92951154/186152217-86ec34ad-24db-4ee4-9102-4d3961edfe88.png)

**Comment by MartinSmeyer** [comment]
Hi @AminSeffo,

there is no option for that in the config file.  But you can simply adapt those two lines and recreate the codebook:

https://github.com/DLR-RM/AugmentedAutoencoder/blob/9f0a56f622fabf6200d9f034fcb2eef106997118/auto_pose/ae/dataset.py#L43-L44

**Comment by AminSeffo** [comment]
Hey @MartinSmeyer,
thanks a lot for your response.
I will try it out, I think the main problem is the rotational symmetry of the detected part..

**Comment by AminSeffo** [comment]
> Hi @AminSeffo,
> 
> there is no option for that in the config file. But you can simply adapt those two lines and recreate the codebook:
> 
> https://github.com/DLR-RM/AugmentedAutoencoder/blob/9f0a56f622fabf6200d9f034fcb2eef106997118/auto_pose/ae/dataset.py#L43-L44

should I only change these values and save or create a new **AE_WORKSPACE_PATH**, because I cant realized any differences?

**Comment by AminSeffo** [comment]
> Hi @AminSeffo,
> 
> there is no option for that in the config file. But you can simply adapt those two lines and recreate the codebook:
> 
> https://github.com/DLR-RM/AugmentedAutoencoder/blob/9f0a56f622fabf6200d9f034fcb2eef106997118/auto_pose/ae/dataset.py#L43-L44

I could not realize any changes after changing these two lines to : 
```
        azimuth_range = (0, 2 * np.pi)
        elev_range = (-0.5 * np.pi, 0)
```
After that I executed the following lines:

```
- pip install .
- ae_train exp_group/my_autoencoder
- ae_embed exp_group/my_autoencoder
```
![training_images_499](https://user-images.githubusercontent.com/92951154/187175695-5457af76-dc95-4045-b2e5-2b731bd919e6.png)

- [ ] What I need are only these three views in different combinations (orientations):

The left view, the right view and the top view as can be seen below:

![image(2)](https://user-images.githubusercontent.com/92951154/187176850-7852f8da-ebee-4488-a427-3ba90b3becfa.png)

**Comment by MartinSmeyer** [comment]
The visualization is for the training, but only the codebook/embedding is changed in these two lines. It doesn't hurt that the training still covers the whole pose space as long as the embedding only contains the correct poses. You can visualize the generated rotations using this function:
https://github.com/DLR-RM/AugmentedAutoencoder/blob/9f0a56f622fabf6200d9f034fcb2eef106997118/auto_pose/ae/dataset.py#L177

If you still want to change it for training as well, you need to change adapt the code here:
https://github.com/DLR-RM/AugmentedAutoencoder/blob/9f0a56f622fabf6200d9f034fcb2eef106997118/auto_pose/ae/dataset.py#L243

I don't bother much with specific poses, as this process needs to be repeated for every object and thus does not scale. But feel free to engineer it, it will probably give better results.

**Comment by AminSeffo** [comment]
@MartinSmeyer 
thank you a lot. I will try to test it just as you explained.
