### ISSUE TITLE
[question] Does camera matrix K, width and height have to be the same on the model training and on the testing? 

### ISSUE THREAD

**Issue by adalmases-dev** [DLR-RM/AugmentedAutoencoder#122]
I am working on a perception module where I work with different cameras. (some kinects, some webcams, ...) each with its own characteristics. I am using the "m3_interfaces" approach with a custom maskrcnn detection model. 

I would like to know if I need to train a 3d model (for different objects) for each different camera and then use it according to the camera, or can I just train a common model and then on the execution time specify which K, width and height the camera has? 

Thanks

**Comment by MartinSmeyer** [comment]
Hey @Albertdalmen,


> or can I just train a common model and then on the execution time specify which K, width and height the camera has?

Yes the m3 interface supports this, however the test camera settings shouldn't differ too much from the training camera settings, because the resolution of the input crops (embedding crops vs. test crops) will be different.

**Comment by MartinSmeyer** [comment]
To limit potential failure cases, I would still just train multiple models.
