### ISSUE TITLE
Did you test your approach on YCB-video dataset?

### ISSUE THREAD

**Issue by sjtuytc** [DLR-RM/AugmentedAutoencoder#15]
Hello, the YCB-video dataset is becoming a standard SIXD benchmark for deep learning today. Did you have tested your approach on it? If so, could you provide the corresponding numbers?

**Comment by MartinSmeyer** [comment]
I have not done any quantitative evaluation on ycb yet. If it is in sixd format, it should be straight forward. I might test this someday

**Comment by sjtuytc** [comment]
Actually I get stuck when training AAE for YCB-video models. They are obj file instead of ply and the code keeps in 0% without reporting errors or stopping. Maybe I have to transfer them to standard ply files.

**Comment by MartinSmeyer** [comment]
Here is an evaluation:
https://bop.felk.cvut.cz/leaderboards/bop19_ycb-v/

**Comment by federicotomat** [comment]
Hello,
have you prepared functions to interface with the BOP toolkit for evaluation, in order to test it on YCB-video dataset?
Would they be available in case?
