### ISSUE TITLE
Models_Reconst works well, but Models_CAD shows "No handlers could be found for logger "OpenGL.arrays.numpymodule"ETA:  --:--:-- " 

### ISSUE THREAD

**Issue by xiaomaoo** [DLR-RM/AugmentedAutoencoder#16]
Models_Reconst works well, but Models_CAD show: 
" No handlers could be found for logger "OpenGL.arrays.numpymodule"ETA:  --:--:-- " Segmentation fault (core dumped) "
I have change the MODEL from "reconst" to " cad" in the .cfg file

**Comment by MartinSmeyer** [comment]
reconst stands for reconstruction. The naming comes from the T-LESS dataset where you have on the one hand reconstructed models (with vertex colors) and on the other hand cad models (without vertex colors). So you have to provide a model without vertex color in this case.

**Comment by sinnis1991** [comment]
Then here comes the problem. When I try to load a T-less model with 'cad' as option. it prints "TypeError: must be str, not bytes"
