### ISSUE TITLE
Use my own 3d model, but it seems not right 

### ISSUE THREAD

**Issue by xiaomaoo** [DLR-RM/AugmentedAutoencoder#17]
I replaced the "obj_5.ply" model to my own ply model, which has the same format with the model in the models_reconst.However, it looks wrong when I run "ae_train exp_group/my_autoencoder -d"
Why?
  
![screenshot from 2019-03-05 20-30-00](https://user-images.githubusercontent.com/25716233/53805963-92a58780-3f86-11e9-9cca-010dcd3ad3c3.png)

**Comment by MartinSmeyer** [comment]
Might be the scale of the 3D model. Change the VERTEX_SCALE parameter to 1000 in the train cfg.

**Comment by xiaomaoo** [comment]
Thanks for reply! 
I tried, but didn’t work. 
 I attached my model in the attachment: 
[TGB170.zip](https://github.com/DLR-RM/AugmentedAutoencoder/files/2944275/TGB170.zip)

**Comment by MartinSmeyer** [comment]
Hi, 
additionally to the wrong vertex scale, the model origin is kilometers away from the actual origin. 

I centered the model origin for you. You can use meshlab for it :)
[mymodel_centered.ply.zip](https://github.com/DLR-RM/AugmentedAutoencoder/files/2945287/mymodel_centered.ply.zip)

**Comment by xiaomaoo** [comment]
Thank you  very much!
