### ISSUE TITLE
About the usage of ICP refinement

### ISSUE THREAD

**Issue by backkon** [DLR-RM/AugmentedAutoencoder#26]
HI！
I want yo use ICP algorithm to refine R and t,but there are some questions that bother me...
I konw there is an ICP option in the cfg file and i can set it to TRUE,but what else should i do?
we know that a rgbd camera have a rgb camera and a depth camera,and the function process_pose has two parameters:color_img, depth_img.Should i align depth_img with color_img first?

**Comment by flugenheimer** [comment]
Im curious about this one as well. I have tried both, and the results are worse than not using ICP. 

I also had to go into the renderer.py file in the ICP folder and change the renderer to meshrenderer_phong as I am using reconst files (just a heads up if other people are having problems with that):
def renderer(self):
        #return meshrenderer.Renderer([self.model_path],1,'.',1)
        # if self.model == 'cad':
        # if self.model == 'reconst':
        return meshrenderer_phong.Renderer([self.model_path],1,'.',1)

I am using a realsense D435 camera for RGB and depth with resolution 640 x 480

**Comment by MartinSmeyer** [comment]
I updated the code. Please make sure you also update your aae_retina_webcam config file in your workspace. I also added a parameter "depth_scale" that defines whether depth data is in mm or m.

It is important that color and depth images are aligned in beforehand. Note that for the D435 the FOV is different for color and depth. 

If I find time, I will further improve the ICP interface.
