### ISSUE TITLE
an issue to train autoencoder with LINEMOD 3D models

### ISSUE THREAD

**Issue by mengce97** [DLR-RM/AugmentedAutoencoder#29]
when i train an autoencoder with linemod datasets,i change the cfg like this:

[Dataset]
MODEL: reconst
H: 128
W: 128
C: 3
RADIUS: 500
RENDER_DIMS: (650, 484)
K: [572.4114, 0, 325.2611, 0, 573.5704, 242.0489, 0, 0, 1]
# Scale vertices to mm
VERTEX_SCALE: 10
ANTIALIASING: 8
PAD_FACTOR: 1.2
CLIP_NEAR: 10
CLIP_FAR: 10000
NOOF_TRAINING_IMGS: 20000
NOOF_BG_IMGS: 15000

The vertex scale of linemod is cm, so i change the vertex_scale, the inner cammera matrix of linemod is K: [572.4114, 0, 325.2611, 0, 573.5704, 242.0489, 0, 0, 1], and so on as the render_dims.
However, i still encounter the problem that "object in rendering not visible,have you scaled the vertices to mm?".
Are there any mistakes with the parameters i changed? Any parameters  else i need to change?
Thanks for your reply!

**Comment by mengce97** [comment]
oh,i seem to use the wrong 3D model,however,can u help me with the rest questions?
Is the K and render_dims correct?

**Comment by MartinSmeyer** [comment]
K seems correct, the render dimensions should be 640x480. Vertex scale = 1 since cm is already converted to mm in the code. For the larger objects, you might have to increase the radius to 800 to ensure everything is in the image..

**Comment by mengce97** [comment]
thank u!
