### ISSUE TITLE
Problem about the result of generating training data. [question]

### ISSUE THREAD

**Issue by yikakabu** [DLR-RM/AugmentedAutoencoder#30]
Hi. There is a problem when I generate and check training data.
As the picture shows, the blue part of my model becomes transparent.
![sample batch_screenshot_04 05 2019](https://user-images.githubusercontent.com/38148405/57179455-c2064100-6eb0-11e9-884d-5c99e3e0053f.png)
Could you give any suggestions? Thanks in advance.
And my model is here.
[model.tar.gz](https://github.com/DLR-RM/AugmentedAutoencoder/files/3144404/model.tar.gz)

**Comment by MartinSmeyer** [comment]
Hi!
yes, your model somehow interferes with the antialiasing in the renderer. Simply set ANTIALIASING: 1 in the training config file and it should be fine.

**Comment by yikakabu** [comment]
@MartinSmeyer 
Awesome! That works. Thank you for your tips.
