### ISSUE TITLE
On the Importance of Training Parameters

### ISSUE THREAD

**Issue by filipetrocadoferreira** [DLR-RM/AugmentedAutoencoder#31]
I've been trying to train a model with a custom .ply. Visually the model is correctly being used to generate training images. However, the auto-encoder generates only black images. The training configuration is the used in your results? Any hyper parameter worth changing?

EDIT:
Actually, setting BatchNorm to True changes the behavior of the model. I'll update with new results

**Comment by MartinSmeyer** [comment]
Yes, if you have a long/thin/dark object this can happen. Usually simply increasing the bootstrap_ratio to e.g. 10 and setting auxiliary_mask to true is sufficient. Training can take a bit longer so you can increase the iterations a bit too.

**Comment by filipetrocadoferreira** [comment]
Although my object had none of those characteristics, changing bootstrap_ratio and setting aux_mask allowed to train the model.

Thanks! And congratulations on this amazing job
