### ISSUE TITLE
[question] Training a thin model and the test result is not correct

### ISSUE THREAD

**Issue by delnasay** [DLR-RM/AugmentedAutoencoder#32]
Hi!

I trained the AAE with a cad [leaf model](https://github.com/delnasay/LeafModel/blob/master/new_leaf_cad.ply), which I set VERTEX_SCALE: 80, AUXILIARY_MASK: True, BOOTSTRAP_RATIO: 10. The training image is showed below:
![training image](https://github.com/delnasay/LeafModel/blob/master/training_images_29999.png?raw=true)

But when I test in images with `aae_image.py`, the results are not correct. For example, this is one of the images I used:
![origin image](https://github.com/delnasay/LeafModel/blob/master/20190530090431.png?raw=true)

The predict image is
![pred image](https://github.com/delnasay/LeafModel/blob/master/20190530090431_pred.png?raw=true)

It is obviously that the predict result is not correct. 
Could you give me some suggestion for this? Thanks a lot.

**Comment by MartinSmeyer** [comment]
Hi!
So one problem is that the image gets resized to a square image and then looks quite distorted like the output:

![image](https://user-images.githubusercontent.com/18601778/59505511-e7ba3900-8ea5-11e9-9135-e6cb41760088.png)

You can use the fucntion extract_square_patch() from dataset.py to create an undistorted image crop from a tight bounding box. This should improve the result. Also you could map the texture on the model to improve results. 

For this thin object, maybe even a segmentation is sufficient?
