### ISSUE TITLE
[question] Could you please share a trained model or complete package files for some experiment

### ISSUE THREAD

**Issue by KPomagier** [DLR-RM/AugmentedAutoencoder#33]
Hi,
I am wondering if it will be an option to share with me with some trained model or complete package files that are necessary to run your's aae experiment?
If you have a Docker i will be very helpfull.

**Comment by MartinSmeyer** [comment]
Hi,
Sorry, we can't use docker. Where are you stickI have some trained AAE models, do you want any specific?
