### ISSUE TITLE
Could this project run on a machine that has no display connected to it?

### ISSUE THREAD

**Issue by fred2019-dev** [DLR-RM/AugmentedAutoencoder#35]
I have searched among the closed issues and see one reply from the author saying the Offscreen rendering is not supported  and a display is needed. That was several months ago, so now has there been any change? Could it be possible for me to run this project on a machine without display??

Thank you very much!

**Comment by MartinSmeyer** [comment]
No, it is still not supported by glfw. You can prerender images on your machine and copy the cached files to the off-screen machine.
If it is crucial for you, it should not be too difficult to incorporate another renderer in dataset.py. PRs are welcome!
