### ISSUE TITLE
Testing as "Augmented Autoencoder only" means there is no SSD detector used？

### ISSUE THREAD

**Issue by xiaomaoo** [DLR-RM/AugmentedAutoencoder#37]
Testing as "Augmented Autoencoder only" means there is no SSD detector used and won't detect the object in the image or video ?    and only  calculate the 3D Orientation ?
And I have to add my own detector model to the code (aae_webcam.py) ?

**Comment by MartinSmeyer** [comment]
Yes, exactly. However if you train  
https://github.com/fizyr/keras-retinanet
we provide a nice interface for the whole pipeline. See:
https://github.com/DLR-RM/AugmentedAutoencoder#multi-object-rgb-based-6d-object-detection-from-a-webcam-stream
