### ISSUE TITLE
openGL error 1282 

### ISSUE THREAD

**Issue by flugenheimer** [DLR-RM/AugmentedAutoencoder#38]
I just tried to install and run the scripts on a new pc but I am running into this error when running the ae_train exp_group/my_autoencoder -d: 

File "src/errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1282,
	description = 'invalid operation',
	baseOperation = glNamedFramebufferTexture,
	cArguments = (
		array([1], dtype=uint32),
		GL_COLOR_ATTACHMENT0,
		1,
		0,
	)
)

I tried using pip to install pyopengl, and also tried it by using the branch directly, which fixed another opegl bug: https://github.com/mcfletch/PyOpenGL 

I am using CUDA 10.1 and tensorflow 1.14, and the nvidia 390.87 driver on a Quadro P2000 GPU.

**Comment by flugenheimer** [comment]
Hmm solved it by going back to ubuntu 16.04 with CUDA 9.0 and tensorflow 1.12. I knew that this worked at some point.
Issue could be my installation of CUDA, an issue with CUDA 10 and pyopengl  or a lot of other things. If I have the time I will try to look a bit more into it.

**Comment by dfraska-ftl** [comment]
If anyone else runs into this, it appears to be a video driver issue. I personally ran into this issue while accessing my Linux machine through NoMachine (remote desktop software).

**Comment by saqib1707** [comment]
Hey @dfraska-ftl , I am facing this issue and unable to resolve this. Following are my configurations:
python: 3.6.9
TF-GPU: 1.15.0
PyOpenGL: 3.1.5
PyOpenGL Accelerate: 3.1.5
CUDA: 10.0

Which version of OpenGL worked for you ?

**Comment by azuryl** [comment]
> Hey @dfraska-ftl , I faced this issue and somehow manage to resolve this. Following are my configurations: python: 3.6.9 TF-GPU: 1.15.0 PyOpenGL: 3.1.5 PyOpenGL Accelerate: 3.1.5 CUDA: 10.0 I did not had to downgrade PyOpenGL. I was running this inside an ubuntu18.04-based docker container. Therefore in the end, I had to go for headless rendering using EGL. Refer to this for anyone using docker container: [#19 (comment)](https://github.com/DLR-RM/AugmentedAutoencoder/issues/19#issuecomment-522597053)

@saqib1707 I export PYOPENGL_PLATFORM='egl'  but  Not allowed to force software rendering when API explicitly selects a hardware device.

**Comment by ZhenningZhou** [comment]
> Hey @dfraska-ftl , I faced this issue and somehow manage to resolve this. Following are my configurations: python: 3.6.9 TF-GPU: 1.15.0 PyOpenGL: 3.1.5 PyOpenGL Accelerate: 3.1.5 CUDA: 10.0 I did not had to downgrade PyOpenGL. I was running this inside an ubuntu18.04-based docker container. Therefore in the end, I had to go for headless rendering using EGL. Refer to this for anyone using docker container: [#19 (comment)](https://github.com/DLR-RM/AugmentedAutoencoder/issues/19#issuecomment-522597053)

Hi, I face the same problem now and think this is because of the driver, so what's the version of your Nvidia driver?
