### ISSUE TITLE
Will this repo implement 'Multi-path Learning for Object Pose Estimation Across Domains'?

### ISSUE THREAD

**Issue by filipetrocadoferreira** [DLR-RM/AugmentedAutoencoder#43]
Are you thinking about sharing the code of the work done in 'Multi-path Learning for Object Pose Estimation Across Domains'?

**Comment by MartinSmeyer** [comment]
Yes, definitely :) There is still a good portion of code cleanup necessary, but I will try my best to make it available soon.

**Comment by filipetrocadoferreira** [comment]
Awesome! That's a nice work and these are good news!
