### ISSUE TITLE
Evaluation on Custom dataset and occasional fail

### ISSUE THREAD

**Issue by kuwt** [DLR-RM/AugmentedAutoencoder#47]
Thanks for the code for evaluation. I have trained it on a custom object:
![image](https://user-images.githubusercontent.com/20258451/66034499-ecc9f380-e53b-11e9-82ac-0b3043f0b00b.png)

I tested it on 3 samples(first row) and the result is (second row):
![image](https://user-images.githubusercontent.com/20258451/66035415-aaa1b180-e53d-11e9-8bd8-5ab729415181.png)

The middle object has an incorrect output.
What is your idea on this issue?

**Comment by kuwt** [comment]
I changed the crop image aspect ratio. The result is better. 
![image](https://user-images.githubusercontent.com/20258451/66036692-7b407400-e540-11e9-9b66-c61b29716ebe.png)

**Comment by MartinSmeyer** [comment]
Yes, I assume you used the aae_image.py script to generate these results? In contrast to the other test scripts, it does not pad the input images before inserting them into the AAE but simply resizes them to a quadratic fixed size. This introduces strong distortions if your original input is not quadratic and therefore the pose estimation fails. 
So simply padding with black pixels up to a quadratic aspect ratio should prevent that. I will add the padding also to aae_image.py.

**Comment by alexey-kashapov** [comment]
@MartinSmeyer 
Also, I have not good results using aae_image.py
Where could it be a problem? Do you have any suggestions?
![1_resized](https://user-images.githubusercontent.com/32935044/67535307-07593d80-f6a0-11e9-8f30-cb2af79d439d.png)
![1_res](https://user-images.githubusercontent.com/32935044/67535312-0aecc480-f6a0-11e9-878f-5be9e718b837.png)
![2_resized](https://user-images.githubusercontent.com/32935044/67535326-1809b380-f6a0-11e9-99b2-b1268721c2d7.png)
![2_res](https://user-images.githubusercontent.com/32935044/67535336-22c44880-f6a0-11e9-9697-37ecbeb73700.png)
![3_resized](https://user-images.githubusercontent.com/32935044/67535341-26f06600-f6a0-11e9-884d-61fd0b72fbbe.png)
![3_res](https://user-images.githubusercontent.com/32935044/67535344-29eb5680-f6a0-11e9-95a2-611db0e92cc9.png)
![4_resized](https://user-images.githubusercontent.com/32935044/67535345-2c4db080-f6a0-11e9-9756-2a8fd1e86ac2.png)
![4_res](https://user-images.githubusercontent.com/32935044/67535346-2e177400-f6a0-11e9-8a11-179575754972.png)
![5_resized](https://user-images.githubusercontent.com/32935044/67535349-3079ce00-f6a0-11e9-84f1-a7683b8abaa0.png)
![5_res](https://user-images.githubusercontent.com/32935044/67535351-32439180-f6a0-11e9-87b4-53357d0c90c1.png)
![6_resized](https://user-images.githubusercontent.com/32935044/67535353-340d5500-f6a0-11e9-97e6-fe974fcf4756.png)
![6_res](https://user-images.githubusercontent.com/32935044/67535359-353e8200-f6a0-11e9-841c-8412d0f019b2.png)

**Comment by alexey-kashapov** [comment]
### Here are my training figures

![training_images_9999](https://user-images.githubusercontent.com/32935044/67535589-4c31a400-f6a1-11e9-950e-8ce653d4d024.png)
![training_images_19999](https://user-images.githubusercontent.com/32935044/67535591-4dfb6780-f6a1-11e9-993e-9d559be30ee2.png)
![training_images_29999](https://user-images.githubusercontent.com/32935044/67535594-4f2c9480-f6a1-11e9-9233-76e9803d4174.png)


.
