### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by YinnnnnnnnS** [DLR-RM/AugmentedAutoencoder#49]
**Describe the bug**
1. I can't use "ae_train exp_group/my_autoencoder -d"   becauese " command not found"
    so I use "python ae_train exp_group/my_autoencoder -d"
2.When I use "python ae_train exp_group/my_autoencoder -d", after loading pictures, the program quit in "reconstr_train = sess.run(decoder.x, feed_dict={queue.x:this_x})" (line 140 in ae_train.py)
the bug info is "Segmentation fault (core dumped)"
3.And when I check the shape of this_x and queue.x, the output is "('queue.x', TensorShape([Dimension(None), Dimension(128), Dimension(128), Dimension(3)]))
('this_x', (128, 128, 3))"
4.I have also changed the batch size and the number of pictures, it seems not to be the memory problem of GPU

**System Info**
 * GPU GeForce GTX 1080
 * python2.7
 * tensorflow 1.9.0
 * Ubuntu 16.04

**Comment by MartinSmeyer** [comment]
Do you have .local/bin/ in your PATH? Then `ae_train ...` should work after `pip install --user .`

Did you try to run this on a machine without a display? Does `ae_train` without `-d` work?

**Comment by DateBro** [comment]
@YinnnnnnnnS 1. Maybe you can try to add  'export PATH=$PATH:/home/xxx/.local/bin/' in your ~/.bashrc file to solve the 'command not found' problem.

**Comment by MartinSmeyer** [comment]
closed because inactive
