### ISSUE TITLE
Trying to reproduce the results in T-LESS failed.

### ISSUE THREAD

**Issue by qyz55** [DLR-RM/AugmentedAutoencoder#51]
Hello, thank you for your wonderful work! Recently I tried to reproduce the results on T-LESS. More specifically, the "w/ GT 2D BBs" part of AAE without ICP. For training and evaling, I both used the same parameters in README.md. And I succeeded in reproducing the result of object 05(I got recall of vsd 66.1, which is similar to the result 66.7 reported in article). But when I used the same parameters for object 19 and 20, I only got 13.1 and 11.2 while the results in article are 50.75 and 37.75. I repeated the experiments twice, but no difference seemed to be seen. Can you tell some skills in adjusting the parameters? Or can you share your trained models or estimated pose files on T-LESS? Thank you for your assistance!

**Comment by qyz55** [comment]
In addition, I checked the output images of objedct 19 and 20. It seems the error mainly comes from the translation error. The threshold \tau in VSD is 20mm, while the average translation error in object 19 is 30mm. Rotations seem good obeserved from the output images.

**Comment by MartinSmeyer** [comment]
Did you train object 19 and 20 with the CAD model? Since the 3D reconstructions completely misses the pins, I am training on the textureless CAD models for objects 19-23 (as mentioned in the paper). The missing pins are a problem for the projective translation estimation since the geometry is changed. If you don't manage, I can send you the model when I am back from ICCV.

**Comment by qyz55** [comment]
Problem solved! The key point is the pin. After I used the CAD model, the vsd of object  19 is very close to the result in the paper. Thanks a lot!

**Comment by qyz55** [comment]
Sorry to bother, but

**Comment by qyz55** [comment]
Sorry to bother. Although I succeeded in object 19 and 21, the result of object 20, 22, 23 is still lower than the result in the paper about 10% on vsd. Would you mind share your  results on object 19-23? A zip of yaml file of the poses is the best. Or checkpoints is okay as well. Would you mind share your results on google cloud or one drive or send to my email: jiangyuh1112@gmail.com ? Thanks a lot!

**Comment by MartinSmeyer** [comment]
Alright, I sent you an email with the checkpoints.

For the CAD models, you can set the probability of the color inversion augmentation higher since there is no texture information that gets destroyed:
Sometimes(0.5, Invert(0.5, per_channel=True))

**Comment by qyz55** [comment]
Got the model, and the vsd recall is even a little better than the article report. Great appreciation to you!
