### ISSUE TITLE
[question] How to evaluate the model with object detector?

### ISSUE THREAD

**Issue by alexey-kashapov** [DLR-RM/AugmentedAutoencoder#52]
1. I trained Autoencoder for my 3d model
2. I trained keras-retinanet for detecting my object.
How can I evaluate the whole system to get 6DOF of the object in a single RGB image?
Thank you!

**Comment by MartinSmeyer** [comment]
Hi Alexey,
simply adapt aae_retina_image_pose.py to input your image:
https://github.com/DLR-RM/AugmentedAutoencoder#multi-object-rgb-based-6d-object-detection-from-a-webcam-stream
I will push a script for single image processing soon.
