### ISSUE TITLE
What does K_test in aae_retina_webcam.cfg mean? [question]

### ISSUE THREAD

**Issue by CaptainTimberTim** [DLR-RM/AugmentedAutoencoder#54]
Hi, 
this maybe obvious but I do not know what these values are for? Are they some camera parameters from a calibration? If so I would need to change them, when I use my webcam, don't I? 
The first tests seemed to work Ok even without changing the K_test values, but I would like to be sure. 
Thanks for the great work though, much appreciated!

**Comment by MartinSmeyer** [comment]
Yes, K_test are the camera intrinics of your Webcam which are necessary for accurate pose estimation. If your camera does not have fixed intrinsics that you can look up, use opencv to find out the intrinics.
