### ISSUE TITLE
Getting empty training inages.

### ISSUE THREAD

**Issue by capslocknanda** [DLR-RM/AugmentedAutoencoder#56]
![training_images_9999](https://user-images.githubusercontent.com/46029468/69007526-b0324a00-0979-11ea-9f74-36d8fb5f2983.png)

**Describe the bug**
getting black empty training images

**System Info**
Describe the characteristic of your environment:
 * GPU GTX 1080
 * Python 2.7
 * OpenGL 4.6
 * Versions of any other relevant libraries

**Additional context**

**Comment by MartinSmeyer** [comment]
Hi,
try to change the VERTEX_SCALE parameter in your train config to 1000.

**Comment by capslocknanda** [comment]
My training image is looking like this.
The model surface is not straight. Can you help me with this?


![training_images_3199](https://user-images.githubusercontent.com/46029468/69253929-643d0a80-0bf0-11ea-8013-7c1c63948664.png)

**Comment by MartinSmeyer** [comment]
Hi,
seems like your object has a weird size. Reduce either the Vertex Scale to 100 or try to reduce your rendering distance.

**Comment by capslocknanda** [comment]
thank you for the information.
