### ISSUE TITLE
Weired ICP performance

### ISSUE THREAD

**Issue by pengsida** [DLR-RM/AugmentedAutoencoder#59]
Hi,
Your work is very very awesome, but I find something that confused me, which is that ICP improves the performance so much.
The approach described in your paper follows a detector.
Once the detection result is wrong, the initial pose could be far away from the ground truth pose, which makes the ICP hard to reach the optimal point.
One plausible reason is that ICP can handle most poses whose 2d coordinates are within the image.
Please tell me why ICP performs so good, since I am so curious.

**Comment by MartinSmeyer** [comment]
in the paper we use visual surface discrepancy (VSD) as a metric. VSD is very sensitive to offsets along the camera axis. While the orientation and 2D translation estimate are often correctly predicted using RGB data, the distance estimate using only RGB is often a bit inaccurate. A simple depth-based ICP along the camera thus lets the metrics increase a lot.

**Comment by pengsida** [comment]
Thanks for clarification!
