### ISSUE TITLE
[question] About the occlusion during generating training images.

### ISSUE THREAD

**Issue by zeal-github** [DLR-RM/AugmentedAutoencoder#67]
In the paper, it said: applying occlusions using random object masks or black squares.
However, in the code I found that these two flags are set to be false:
```
 [Augmentation]
REALISTIC_OCCLUSION: False
SQUARE_OCCLUSION: False
```
Do you apply occlusions in your final experiments?

**Comment by MartinSmeyer** [comment]
Hi,
Yes we apply occlusion in the form of spatial dropout as this is cheaper to compute as realistic occlusions and has similar effects. See some lines below:
`Sometimes(0.5, CoarseDropout( p=0.2, size_percent=0.05) ),`
