### ISSUE TITLE
YCB-video dataset

### ISSUE THREAD

**Issue by federicotomat** [DLR-RM/AugmentedAutoencoder#73]
Hi @MartinSmeyer,
have you prepared functions to interface with the BOP toolkit for evaluation, in order to test it on YCB-video dataset?
Would they be available in case?

**Comment by MartinSmeyer** [comment]
Hi @federicotomat ,
I have an interface, but it also interfaces with some internal code.. Do you just need an example how to evaluate with the bop_toolkit or do you want to replicate the bop results for ycbv with the AAEs? IIn the first case I can send you some sample code. 

The evaluations numbers are available here: 
https://bop.felk.cvut.cz/leaderboards/bop19_ycb-v/

In future, I might also provide the scripts for generating those results, but it is basically just stitching together a MaskRCNN with AAEs from this repo.

**Comment by federicotomat** [comment]
Thanks @MartinSmeyer for the reply,

would it be possible to have the evaluation results carried out on YCB-video for the individual objects?
In particular, I am interested in the vsd value calculated with the GT.

**Comment by MartinSmeyer** [comment]
Alright! So, I have the ycbv predictions in bop csv format:

[sundermeyer-vivo_ycbv-test.zip](https://github.com/DLR-RM/AugmentedAutoencoder/files/4787858/sundermeyer-vivo_ycbv-test.zip)

The online evaluation tool does not output the per object scores. However, you can simply pass the csv files to 

https://github.com/thodan/bop_toolkit/blob/master/scripts/eval_bop19.py

to generate the detailed results. I hope that helps :)

**Comment by federicotomat** [comment]
Thank you very much

**Comment by hiyyg** [comment]
Hi @MartinSmeyer , how do you render with BOP ycbv models? It seems the meshrenderers in this codebase only support meshes with vertex color, but ycbv models are meshes with texture maps. Should I convert the texture maps to vertex color?

**Comment by MartinSmeyer** [comment]
Yes exactly, I converted the textures to vertex colors

**Comment by hiyyg** [comment]
@MartinSmeyer May I ask how you converted the textures to vertex colors? I tried it with meshlab but the quality of the converted model was very bad.

**Comment by federicotomat** [comment]
Hi @hiyyg,  if it can come in handy, I have trained on YCB models by changing the renderer with the [bop renderer](https://github.com/thodan/bop_renderer) of the bop toolkit. (I tried also with [this](https://github.com/mmatl/pyrender)).

If I remember correctly you need to change only from [this](https://github.com/DLR-RM/AugmentedAutoencoder/blob/master/auto_pose/ae/dataset.py#L244) part of the code.

An idea of the quality of the results, that I have obtained after 30000 iterations, are shown below (using the cracker-box model):
![training_images_29999](https://user-images.githubusercontent.com/39094212/93233153-09763000-f77b-11ea-906a-bd8daea8ca3e.png)

I took this opportunity to thank @MartinSmeyer again, for his work.
