### ISSUE TITLE
Multi-Path Learning release

### ISSUE THREAD

**Issue by safoex** [DLR-RM/AugmentedAutoencoder#74]
Hi Martin, many thanks for your works, I know you are probably quite busy now, but do you plan to release a code for https://arxiv.org/abs/1908.00151 soon? If so, is it based on TF1.0 like the original AAE?

**Comment by MartinSmeyer** [comment]
Yes, it will be and I am actually releasing parts of it today

**Comment by MartinSmeyer** [comment]
it is available now

**Comment by safoex** [comment]
Great, thank you!
