### ISSUE TITLE
question

### ISSUE THREAD

**Issue by whwme** [DLR-RM/AugmentedAutoencoder#76]
**Describe the bug**
using eglembedding ..:   0% |                                                  | 0 / 92232 ETA:  --:--:--  Traceback (most recent call last):   File "/home/whw/.local/bin/ae_embed", line 8, in <module>     sys.exit(main())   File "/home/whw/.local/lib/python3.6/site-packages/auto_pose/ae/ae_embed.py", line 83, in main     codebook.update_embedding(sess, batch_size)   File "/home/whw/.local/lib/python3.6/site-packages/auto_pose/ae/codebook.py", line 211, in update_embedding     batch, obj_bbs_batch = self._dataset.render_embedding_image_batch(a, e)   File "/home/whw/.local/lib/python3.6/site-packages/auto_pose/ae/dataset.py", line 343, in render_embedding_image_batch     obj_bb = view_sampler.calc_2d_bbox(xs, ys, render_dims)   File "/home/whw/.local/lib/python3.6/site-packages/auto_pose/ae/pysixd_stuff/view_sampler.py", line 11, in calc_2d_bbox     bbTL = (max(xs.min() - 1, 0),   File "/home/whw/anaconda3/envs/AAE/lib/python3.6/site-packages/numpy/core/_methods.py", line 34, in _amin     return umr_minimum(a, axis, None, out, keepdims, initial, where) 
ValueError: zero-size array to reduction operation minimum which has no identity .

**System Info**
Describe the characteristic of your environment:
GPU:2080ti
python=3.6
OpenGL version string: 4.6.0 NVIDIA 440.82

**Comment by sinnis1991** [comment]
I met with the same problem

**Comment by MartinSmeyer** [comment]
Hi!

Which objects are you using? The training (ae_train) worked for you and completed? I just tried and ae_embed works fine with python 3.7 for me after solving a small python 2/3 compatiblity issue.

This issue usually appears if
1.) The object's coordinate frame origin is defined outside the object --> Center it with e.g. meshlab
or
2.) The object is defined in m when mm are expected. --> Change in train config: VERTEX_SCALE: 1000

Does this solve your issue?

**Comment by whwme** [comment]
> Hi!
> 
> Which objects are you using? The training (ae_train) worked for you and completed? I just tried and ae_embed works fine with python 3.7 for me after solving a small python 2/3 compatiblity issue.
> 
> This issue usually appears if
> 1.) The object's coordinate frame origin is defined outside the object --> Center it with e.g. meshlab
> or
> 2.) The object is defined in m when mm are expected. --> Change in train config: VERTEX_SCALE: 1000
> 
> Does this solve your issue?
Hi!  
I used ‘cat' of LINEMOD_singleshot6D dataset. I have finished the 'ae_train exp_group/my_autoencoder'  ,it took about two hours.   Thanks for  your suggestions,   I will try about it  and reply to you.

**Comment by whwme** [comment]
Hi!
I used ‘cat' of LINEMOD_singleshot6D dataset. I have finished the 'ae_train exp_group/my_autoencoder' ,it took about two hours. Thanks for your suggestions, I will try about it and reply to you.

**Comment by sinnis1991** [comment]
I have checked my code and find it may help. My problem is that the camera intrinsic is wrong. Anyway, this problem might be caused by that the object could not apear intact in the image. Check your training data, fix it until the training data where the object is shown wholely.

**Comment by MartinSmeyer** [comment]
Good point, please always set the camera intrinsics, i.e. K, of the corresponding dataset. Otherwise the object might not appear inside the image in which case the mask becomes zero sized.

**Comment by whwme** [comment]
thanks all of you ! I have solved this problem, which is caused by the data set.When I tested it, the  prediction of  3D Orientation  was a bit off @MartinSmeyer @sinnis1991
