### ISSUE TITLE
Bug while loading ground truth masks

### ISSUE THREAD

**Issue by safoex** [DLR-RM/AugmentedAutoencoder#77]
**Describe the bug**
Attempting to run [evaluation with ground truth bboxes](https://github.com/DLR-RM/AugmentedAutoencoder/tree/multipath#evaluate-and-visualize-6d-pose-estimation-of-mp-encoder-with-ground-truth-bounding-boxes), I got an error with loading ground truth masks:
`
Traceback (most recent call last):
  File "/home/safoex/.local/bin/ae_eval", line 8, in <module>
    sys.exit(main())
  File "/home/safoex/Documents/libs/AugmentedAutoencoder/auto_pose/eval/ae_eval.py", line 136, in main
    test_img_crops, test_img_depth_crops, bbs, bb_scores, visibilities = eval_utils.get_gt_scene_crops(scene_id, eval_args, train_args, load_gt_masks = gt_masks)
  File "/home/safoex/Documents/libs/AugmentedAutoencoder/auto_pose/eval/eval_utils.py", line 66, in get_gt_scene_crops
    (H_AE, W_AE), visib_gt=visib_gt,inst_masks=gt_inst_masks)
  File "/home/safoex/Documents/libs/AugmentedAutoencoder/auto_pose/eval/eval_utils.py", line 195, in generate_scene_crops
    mask = inst_masks[view]
IndexError: list index out of range
`
Most likely, this is because code references local path [e.g. here](https://github.com/DLR-RM/AugmentedAutoencoder/blob/09a57e45cc4809156a59968056f1ca21e272aea7/auto_pose/eval/eval_utils.py#L59). 

**System Info**
Describe the characteristic of your environment:
 * 1650/ dell xps 7590
 * Python 3.6
 * OpenGL version

**Additional context**
There were few other small bugs, mostly with py2-3 compatibility in provided replacement for sixd_toolkit. E.g. [wrong tabulation here](https://github.com/DLR-RM/AugmentedAutoencoder/blob/09a57e45cc4809156a59968056f1ca21e272aea7/auto_pose/ae/dataset.py#L539) and next line. As soon as I manage to run tests correctly, I will be happy to make a pull request resolving everything I faced!

**Comment by MartinSmeyer** [comment]
Thanks for testing @safoex 

Sorry about the local path, I removed it. I adapted the README, you can now download the gt_masks [here](https://dlrmax.dlr.de/get/540391e2-597e-5bfa-80b1-f74b9ea10db1/) and point the 'external' parameter in the eval config to that path.

**Comment by MartinSmeyer** [comment]
PS: PRs are always welcome, thanks!

**Comment by shawnlin427** [comment]
@safoex Hi, thanks for your testing. I wonder that how do you successfully train the model on gtx1650? I modified the batch-size to 1 but still raise "Resource exhausted" error. Looking for your replying!
