### ISSUE TITLE
Missing file cfg_m3vision when initing 

### ISSUE THREAD

**Issue by bokorn** [DLR-RM/AugmentedAutoencoder#78]
Sorry if I missed a step in the install, but I keep getting this error when I call ae_init_workspace for the multipath version. 

`FileNotFoundError: [Errno 2] No such file or directory: '/home/bokorn/.local/lib/python3.6/site-packages/auto_pose/ae/cfg_m3vision'
`
There doesn't seem to be a cfg_m3vision directory or file in auto_pose/ae/. This doesn't seem to be part of the original ae_init_workspace. Thank you for your assistance.

**Comment by MartinSmeyer** [comment]
Thanks, that seems like a left over from our internal code. Should be fixed now.
