### ISSUE TITLE
ae_init_workspace: command not found

### ISSUE THREAD

**Issue by eyildiz-ugoe** [DLR-RM/AugmentedAutoencoder#8]
The preparation commands are somehow unclear. 

Starting from:

`export AE_WORKSPACE_PATH=/path/to/autoencoder_ws  `

Is this workspace supposed to be where we clone the repository? If not, we need to create another folder for this. Is this the case? Please clarify this.

Moving on:

The command of `ae_init_workspace` returns `ae_init_workspace: command not found`, which means due to the unclear instructions, something is not really installed right. Whatever the workspace is at, whether it's a separate folder or it's the cloned repository, this error is thrown anyway.

Last but not least:

`(if installed locally, make sure .local/bin/ is in your PATH)`, if installed what exactly? A lot of installations through pip were done, are you referring to those? If not, what installation are you referring to? The `setup.py` of the repository? 

A clearer set of instructions here would be really, really useful.

**Comment by HuaWeitong** [comment]
> Okay, here is how to get rid of the command not found error:
> 
> 1. Clone the repository.
> 2. Install the pip packages.
> 3. Go to the cloned repository on your computer, in my case `AugmentedAutoencoder`.
> 4. Use the command `pip install --user .` here. It will install `auto-pose`.
> 5. Get out of this folder, and create another one somewhere of your choice. Edit the .bashrc accordingly.
> 6. Go into the folder you created. Execute `ae_init_workspace` here.

Hello, I followed this and created "autoencoder_ws" under "~/.local/bin/", but there is still  `ae_init_workspace: command not found` error. Could you please help me?

**Comment by HuaWeitong** [comment]
Where to create "autoencoder_ws" and what to add to .bashrc?
