### ISSUE TITLE
Object in Rendering not visible

### ISSUE THREAD

**Issue by Zaxorn** [DLR-RM/AugmentedAutoencoder#81]
Hello, sorry for bothering but I really appreciate your work and I want to make it work for my use-case.
I created a custom model.ply but when i try to train the autoencoder I get the warning

Object in Rendering not visible. Have you scaled the vertices to mm?

I tryed to change the vertex_scale parameter in cfg file but nothing.

Here is the 2 model I wanted to work on

[test_1.zip](https://github.com/DLR-RM/AugmentedAutoencoder/files/4966955/test_1.zip)
[test_2.zip](https://github.com/DLR-RM/AugmentedAutoencoder/files/4966959/test_2.zip)

Let me know what it is wrong. Thanks in advance

**Comment by Zaxorn** [comment]
Ok, I needed to significantly augment the object dimension. It's just strange that changing the vertex_scale parameter didn't work.

**Comment by ajal-fh** [comment]
Hi,
 
The same warning is appearing while training on a custom model. The model dimensions are in m (the highest dimension is around 1m) and as instructed 'VERTEX_SCALE' parameter was set to 1000. Do we have to  scale down the model? Thanks in advance

**Comment by Zaxorn** [comment]
Hello,

I'm using Blender to export the .ply models and dimensions of my objects are around 10-20 meters. Using VERTEX_SCALE = 1 works fine for me.
