### ISSUE TITLE
Porting to TensorRT

### ISSUE THREAD

**Issue by davideCremona** [DLR-RM/AugmentedAutoencoder#86]
Hi, is it possible to port a trained Augmented Auto-Encoder to TensorRT for inference on embedded devices (e.g. Jetson TX2 that you used in the demo)

Thanks,
Davide.

**Comment by MartinSmeyer** [comment]
I did not use tensorrt in my demo, however it should be possible. The AAE is also integrated in the mostly closed source Nvidia Isaac sdk for Jetson platforms where it is presumably optimized using tensorrt:

https://docs.nvidia.com/isaac/archive/2020.1/packages/object_pose_estimation/doc/ae_3d_object_pose_estimation.html

**Comment by davideCremona** [comment]
This is great! Thank you for the link, I'll surely use it.
