### ISSUE TITLE
ValueError: need more than 3 values to unpack

### ISSUE THREAD

**Issue by eyildiz-ugoe** [DLR-RM/AugmentedAutoencoder#9]
I'm trying to run `ae_train exp_group/my_autoencoder -d` with a .ply model of mine (which is not a CAD model) and I receive the following error:

```
Instructions for updating:
Use the retry module or similar alternatives.
128 128 3
[[8, 8], [16, 16], [32, 32], [64, 64]]
(?, 128, 128, 3)
(?, 128, 128, 3)
Traceback (most recent call last):20000 ] |                                                                       | (ETA:  --:--:--) 
  File "/home/username/.local/bin/ae_train", line 10, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/ae/ae_train.py", line 90, in main
    dataset.get_training_images(dataset_path, args)
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 93, in get_training_images
    self.render_training_images()
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 246, in render_training_images
    bgr_x, depth_x = self.renderer.render( 
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/ae/utils.py", line 15, in decorator
    setattr(self, attribute, function(self))
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 75, in renderer
    float(self._kw['vertex_scale'])
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/meshrenderer/meshrenderer_phong.py", line 45, in __init__
    for vertex, normal, color, faces in attributes:
ValueError: need more than 3 values to unpack
```

Note that the suggestion reported in https://github.com/DLR-RM/AugmentedAutoencoder/issues/7, did not solve my problem. And if I change it to cad in the config file, I get a `Segmentation Fault`.

In order to help debugging, I am also sharing my .ply model with you:[ bay.ply 
](https://owncloud.gwdg.de/index.php/s/GunQ4qerHRMmoJO/download)
My Blender can visualize this .ply, so I don't think the problem lies within there.

**Comment by MartinSmeyer** [comment]
Hi!

your model is in meters, did you change the vertex_scale parameter to 1000? (it's required in mm)

Please do that and set the model parameter to cad again

I had no problems with the training after doing that

**Comment by eyildiz-ugoe** [comment]
> your model is in meters, did you change the vertex_scale parameter to 1000? (it's required in mm)
Please do that and set the model parameter to cad again

@MartinSmeyer Hi, for some reason I cannot see the reply in any of the issues but I have it in my e-mail, hence I am replying here. 

Thank you for your rapid response. I have acquired the models from another source, and yes I have confirmed that they are scaled. However, I don't know how to change this parameter. Is it on Blender? If so, could you tell me how you did it? I know it's not related to this repository but I really would like to try the Encoder, therefore I would appreciate if you could tell me how to set it back.

**Comment by MartinSmeyer** [comment]
Your segmentation fault is not related to 

"ValueError: need more than 3 values to unpack" 

which only happens if no vertex color is found in the 3d model while the MODEL parameter is set to "reconst".

I just meant the vertex_scale parameter in the training config.

Closing this issue because of the duplicate.

**Comment by MartinSmeyer** [comment]
see [#10]

**Comment by beingkartik** [comment]
Hey, were you able to solve this problem? I'm facing the exact issue.
