### ISSUE TITLE
Multi path model link is not available.

### ISSUE THREAD

**Issue by YoSaRic** [DLR-RM/AugmentedAutoencoder#91]
Hello,
I have read your Multi-Path Encoder paper and eager to try the code, but sadly the download link of pretrained model [obj1_18_v2.zip](https://dlrmax.dlr.de/get/e28d4aee-a538-517e-aa6e-9c600162b0ae/) is out of date. The link was available till Dec. 15 and today is Dec. 21.
Would you give me a favor of providing me the model in some way?
Thank you.

**Comment by MartinSmeyer** [comment]
Hi,
oh sorry about that! I updated the link. I also updated the README and the code so that you can more easily run the model on the BOP challenge and your own data. Have a look at the README in the multipath branch :)
