### ISSUE TITLE
Possible to run on a Smartphone?

### ISSUE THREAD

**Issue by d-lay** [DLR-RM/AugmentedAutoencoder#93]
Hi, I was wondering if it might be possible to run your 6D Pose Estimator even on the limited hardware of a smartphone. Before diving too deep into it, I wanted to get the opinion of more experienced people in the field.

If you think it is possible, is a rough estimation for fps possible (Lets assume it would run on an [Adreno 650 mobile GPU](https://en.wikipedia.org/wiki/Adreno))?

If you think it is not possible could you briefly elaborate on the reasons.

Any insights are appreciated. Thank you very much!

**Comment by MartinSmeyer** [comment]
I have not tried it on a smartphone, but I tried it on a Jetson TX2 where you can run it in real-time. The model size can be reduced by changing the NUM_FILTER parameter in the training config. The codebook requires around 40MB in fp32 but could also be reduced.

**Comment by d-lay** [comment]
Thank You for your reply!That sound already quite promising

**Comment by MartinSmeyer** [comment]
No I think your assumptions are valid. Keep in mind that this is per object though. I ran it on a couple of objects in parallel on the tx2
