### ISSUE TITLE
Hi, I found your work very intersting, but I have one question, can it work on a textured object something like attached gltf object below

### ISSUE THREAD

**Issue by laxmaniron** [DLR-RM/AugmentedAutoencoder#94]
object link: https://drive.google.com/file/d/1s4F88uIuJUiAX03yc66fc3-kIYueb23W/view?usp=sharing

**Comment by MartinSmeyer** [comment]
I suppose yes, but you need to transform it into a .ply file with vertex colors. User e.g. meshlab for that.
